# Generated by Django 5.2.4 on 2025-09-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
